export { default as Container } from './Container';
export { default as Section } from './Section';
export { default as SectionTitle } from './SectionTitle';
export { default as Logo } from './Logo';
export { default as NavBar } from './NavBar.tsx';
export { default as CardNews } from './CardNews.tsx';
export { default as IconsBlock } from './IconsBlock.tsx';
export { default as PageWrapper } from './PageWrapper';
export { default as Sponsors } from './Sponsors';
